/** Plain-language definitions surfaced as tooltips. Keep each to one or two sentences. */
export const GLOSSARY = {
  utilization: 'Hours of work divided by the hours people can actually work. 90% means nine of every ten available hours are spoken for.',
  target: 'The utilization a team is planned to run at, for example 80%. The 20% left over covers peaks, sick days, and surprises. A team is over capacity when its work needs more than that.',
  productive: 'Paid hours minus shrinkage. The hours that can actually go to work.',
  shrinkage: 'The share of paid hours that never reach the work: vacation, training, meetings, sick time.',
  gap: 'Hours of work beyond what the team can handle at its target utilization. Zero means the team is within capacity.',
  required: 'People needed to do this month’s work at the target utilization.',
  shortfall: 'People required minus people available.',
  run: 'Recurring work driven by volume: cases, tickets, implementations, projects.',
  initiative: 'People assigned to strategic initiatives while those are active. They come out of the same hours as run work.',
  initiativeLoad: 'Of all the hours the teams have available, the share that goes to strategic initiatives. The rest goes to day-to-day work.',
  exposure: 'Revenue that depends on initiatives, weighted by each one’s odds of failing. When the teams doing an initiative are over capacity, its odds of failing go up.',
  budget: 'What the modeled teams cost minus the budget set for them. Negative means under budget; positive means over.',
  leadTime: 'Months from deciding to hire to the person actually doing the work.',
  sequencing: 'An initiative that cannot start when planned because something it depends on finishes later.',
  watch: 'Within five points of capacity. Still under, but with no slack left.',
  constrained: 'More work than the team can handle at its target utilization. Work is queuing.',
  severe: 'Above 100%: more work than hours in the month.',
  attrition: 'Expected departures, applied every month from the annual rate. The plan has no automatic backfill.',
  headcount: 'People at the start and end of the year after hires land and attrition takes its share.',
  peakShortfall: 'The single worst team-month: how many more people that team needed than it had.',
  delayed: 'Initiatives that cannot start on their planned month because of a dependency.',
  score: 'A preference score from the weights you set. It ranks options against each other; it does not claim one is objectively best.',
  cost: 'Total modeled cost over the year minus the cost of doing nothing.',
  speed: 'Hours of work still over capacity, added up across all teams and months. Lower means the fix landed sooner and closed more of the gap.',
  contextPenalty: 'Extra time a task takes when the person handling it does not know the client. It applies to one-off work; reusable work carries none.',
} as const;

export type TermKey = keyof typeof GLOSSARY;
